// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://us-central1-auction-app-843e9.cloudfunctions.net',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],

  firebase: {
    apiKey: 'AIzaSyBb6WyiyhVCZd6GLiTpHInNnxqJpi9lGkI',
    authDomain: 'auction-app-843e9.firebaseapp.com',
    databaseURL: 'https://auction-app-843e9.firebaseio.com',
    projectId: 'auction-app-843e9',
    storageBucket: 'auction-app-843e9.appspot.com',
    messagingSenderId: '24212977039'
  }
};



// export const environment = {
//   production: false,
//   version: env.npm_package_version + '-dev',
//   serverUrl: 'https://us-central1-auctionapp-dev.cloudfunctions.net',
//   defaultLanguage: 'en-US',
//   supportedLanguages: ['en-US'],

//   firebase: {
//     apiKey: 'AIzaSyAimvIwO7p0lXo4hNY4kgpMcukRC6GUSO8',
//     authDomain: 'auctionapp-dev.firebaseapp.com',
//     databaseURL: 'https://auctionapp-dev.firebaseio.com',
//     projectId: 'auctionapp-dev',
//     storageBucket: 'auctionapp-dev.appspot.com',
//     messagingSenderId: '24212977039'
//   }
// };
